package GeneratorNPC;

import BasicProfessions.Empty;
import BasicProfessions.*;
import AdvancedProfessions.*;
import java.util.ArrayList;

public class ListOfProfessions {
    ArrayList<Profession> list = new ArrayList();
    
    public ListOfProfessions(){  
        Empty empty = new Empty();
        Akolita akolita = new Akolita();
        Banita banita = new Banita();
        BersekerZNorski berseker = new BersekerZNorski();
        Chlop chlop = new Chlop();
        CiuraObozowa ciuraObozowa = new CiuraObozowa();
        Cyrkowiec cyrkowiec = new Cyrkowiec();
        Cyrulik cyrulik = new Cyrulik();
        Fanatyk fanatyk = new Fanatyk();
        Flisak flisak = new Flisak();
        Giermek giermek = new Giermek();
        Gladiator gladiator = new Gladiator();
        Goniec goniec = new Goniec();
        Gornik gornik = new Gornik();
        Guslarz guslarz = new Guslarz();
        HienaCmentarna hienaCmentarna = new HienaCmentarna();
        Kanciarz kanciarz = new Kanciarz();
        KozakKislevski kozakKislevski = new KozakKislevski();
        Lesnik lesnik = new Lesnik();
        Lowca lowca = new Lowca();
        LowcaNagrod lowcaNagrod = new LowcaNagrod();
        Mieszczanin mieszczanin = new Mieszczanin();
        Mytnik mytnik = new Mytnik();
        Najemnik najemnik = new Najemnik();
        Ochotnik ochotnik = new Ochotnik();
        Ochroniarz ochroniarz = new Ochroniarz();
        Oprych oprych = new Oprych();
        Paz paz = new Paz();
        Podzegacz podzegacz = new Podzegacz();
        PorywaczZwlok porywaczZwlok = new PorywaczZwlok();
        Poslaniec poslaniec = new Poslaniec();
        Przemytnik przemytnik = new Przemytnik();
        Przepatrywacz przepatrywacz = new Przepatrywacz();
        Przewoznik przewoznik = new Przewoznik();
        Rybak rybak = new Rybak();
        RzecznikRodu rzecznikRodu = new RzecznikRodu();
        Rzemieslnik rzemieslnik = new Rzemieslnik();
        Rzezimieszek rzezimieszek = new Rzezimieszek();
        Skryba skryba = new Skryba();
        Sluga sluga = new Sluga();
        Straznik straznik = new Straznik();
        StraznikDrog straznikDrog = new StraznikDrog();
        StraznikPol straznikPol = new StraznikPol();
        StraznikWiezienny straznikWiezienny = new StraznikWiezienny();
        Szczurolap szczurolap = new Szczurolap();
        SzermierzEstalijski szermierzEstalijski = new SzermierzEstalijski();
        Szlachcic szlachcic = new Szlachcic();
        Smieciarz smieciarz = new Smieciarz();
        Tarczownik tarczownik = new Tarczownik();
        UczenCzarodzieja uczenCzarodzieja = new UczenCzarodzieja();
        Weglarz weglarz = new Weglarz();
        Wloczykij wloczykij = new Wloczykij();
        WojownikKlanowy wojownikKlanowy = new WojownikKlanowy();
        Woznica woznica = new Woznica();
        ZabojcaTrolli zabojcaTrolli = new ZabojcaTrolli();
        Zarzadca zarzadca = new Zarzadca();
        Zlodziej zlodziej = new Zlodziej();
        Zak zak = new Zak();
        Zeglarz zeglarz = new Zeglarz();
        Zolnierz zolnierz = new Zolnierz();
        ZolnierzOkretowy zolnierzOkretowy = new ZolnierzOkretowy();
        
        Arcykaplan arcykaplan = new Arcykaplan();
        Arcymag arcymag = new Arcymag();
        Arystokrata arystokrata = new Arystokrata();
        Bard bard = new Bard();
        Biczownik biczownik = new Biczownik();
        Bosman bosman = new Bosman();
        Demagog demagog = new Demagog();
        Dworzanin dworzanin = new Dworzanin();
        Fechmistrz fechmistrz = new Fechmistrz();
        Herold herold = new Herold();
        HersztBanitow hersztBanitow = new HersztBanitow();
        Inzynier inzynier = new Inzynier();
        Kapitan kapitan = new Kapitan();
        Kaplan kaplan = new Kaplan();
        Karczmarz karczmarz = new Karczmarz();
        KsiazeZlodziei ksiazeZlodziei = new KsiazeZlodziei();
        Kupiec kupiec = new Kupiec();
        LesnyDuch lesnyDuch = new LesnyDuch();
        LowcaCzarownic lowcaCzarownic = new LowcaCzarownic();
        LowcaWampirow lowcaWampirow = new LowcaWampirow();
        Majordomus majordomus = new Majordomus();
        Medyk medyk = new Medyk();
        MistrzCieni mistrzCieni = new MistrzCieni();
        MistrzGildii mistrzGildii = new MistrzGildii();
        MistrzMagii mistrzMagii = new MistrzMagii();
        MistrzRzemiosla mistrzRzemiosla = new MistrzRzemiosla();
        MistrzZakonny mistrzZakonny = new MistrzZakonny();
        Nawigator nawigator = new Nawigator();
        Odkrywca odkrywca = new Odkrywca();
        Oficer oficer = new Oficer();
        Oprawca oprawca = new Oprawca();
        Paser paser = new Paser();
        Rajtar rajtar = new Rajtar();
        Reketer reketer = new Reketer();
        Rozbojnik rozbojnik = new Rozbojnik();
        Rycerz rycerz = new Rycerz();
        Sierzant sierzant = new Sierzant();
        Skrytobojca skrytobojca = new Skrytobojca();
        Strzelec strzelec = new Strzelec();
        Szampierz szampierz = new Szampierz();
        Szarlatan szarlatan = new Szarlatan();
        Szpieg szpieg = new Szpieg();
        Uczony uczony = new Uczony();
        Urzednik urzednik = new Urzednik();
        Weteran weteran = new Weteran();
        WedrownyCzarodziej wedrownyCzarodziej = new WedrownyCzarodziej();
        Wlamywacz wlamywacz = new Wlamywacz();
        WybraniecBozy wybraniecBozy = new WybraniecBozy();
        ZabojcaDemonow zabojcaDemonow = new ZabojcaDemonow();
        ZabojcaOlbrzymow zabojcaOlbrzymow = new ZabojcaOlbrzymow();
        Zakonnik zakonnik = new Zakonnik();
        Zwadzca zwadzca = new Zwadzca();
        Zwiadowca zwiadowca = new Zwiadowca();
        
        list.add(empty);
        list.add(akolita);    
        list.add(banita);
        list.add(berseker);
        list.add(chlop);
        list.add(ciuraObozowa);
        list.add(cyrkowiec);
        list.add(cyrulik);
        list.add(fanatyk);
        list.add(flisak);
        list.add(giermek);
        list.add(gladiator);
        list.add(goniec);
        list.add(gornik);
        list.add(guslarz);
        list.add(hienaCmentarna);
        list.add(kanciarz);
        list.add(kozakKislevski);
        list.add(lesnik);
        list.add(lowca);
        list.add(lowcaNagrod);
        list.add(mieszczanin);
        list.add(mytnik);
        list.add(najemnik);
        list.add(ochotnik);
        list.add(ochroniarz);
        list.add(oprych);
        list.add(paz);
        list.add(podzegacz);
        list.add(porywaczZwlok);
        list.add(poslaniec);
        list.add(przemytnik);
        list.add(przepatrywacz);
        list.add(przewoznik);
        list.add(rybak);
        list.add(rzecznikRodu);
        list.add(rzemieslnik);
        list.add(rzezimieszek);
        list.add(skryba);
        list.add(sluga);
        list.add(straznik);
        list.add(straznikDrog);
        list.add(straznikPol);
        list.add(straznikWiezienny);
        list.add(szczurolap);
        list.add(szermierzEstalijski);
        list.add(szlachcic);
        list.add(smieciarz);
        list.add(tarczownik);
        list.add(uczenCzarodzieja);
        list.add(weglarz);
        list.add(wloczykij);
        list.add(wojownikKlanowy);
        list.add(woznica);
        list.add(zabojcaTrolli);
        list.add(zarzadca);
        list.add(zlodziej);
        list.add(zak);
        list.add(zeglarz);
        list.add(zolnierz);
        list.add(zolnierzOkretowy);
        
        list.add(arcykaplan);
        list.add(arcymag);
        list.add(arystokrata);
        list.add(bard);
        list.add(biczownik);
        list.add(bosman);
        list.add(demagog);
        list.add(dworzanin);
        list.add(fechmistrz);
        list.add(herold);
        list.add(hersztBanitow);
        list.add(inzynier);
        list.add(kapitan);
        list.add(kaplan);
        list.add(karczmarz);
        list.add(ksiazeZlodziei);
        list.add(kupiec);
        list.add(lesnyDuch);
        list.add(lowcaCzarownic);
        list.add(lowcaWampirow);
        list.add(majordomus);
        list.add(medyk);
        list.add(mistrzCieni);
        list.add(mistrzGildii);
        list.add(mistrzMagii);
        list.add(mistrzRzemiosla);
        list.add(mistrzZakonny);
        list.add(nawigator);
        list.add(odkrywca);
        list.add(oficer);
        list.add(oprawca);
        list.add(paser);
        list.add(rajtar);
        list.add(reketer);
        list.add(rozbojnik);
        list.add(rycerz);
        list.add(sierzant);
        list.add(skrytobojca);
        list.add(strzelec);
        list.add(szampierz);
        list.add(szarlatan);
        list.add(szpieg);
        list.add(uczony);
        list.add(urzednik);
        list.add(weteran);
        list.add(wedrownyCzarodziej);
        list.add(wlamywacz);
        list.add(wybraniecBozy);
        list.add(zabojcaDemonow);
        list.add(zabojcaOlbrzymow);
        list.add(zakonnik);
        list.add(zwadzca);
        list.add(zwiadowca);
    }

    public ArrayList<Profession> getListOfProfessions() {
        return list;
    }
}
